# Generated by Django 4.0.6 on 2022-07-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='short_bio',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
