# Generated by Django 4.0.6 on 2022-07-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_authorprofile_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='occupation_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
