# Generated by Django 4.0.6 on 2022-07-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_authorprofile_occupation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorprofile',
            old_name='short_bio',
            new_name='about_me',
        ),
    ]
