# Generated by Django 4.0.6 on 2022-07-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_rename_short_bio_authorprofile_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='about_me',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
